# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import predict_pb2 as predict__pb2


class ModelServingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.predict = channel.stream_stream(
                '/model_serving.ModelServing/predict',
                request_serializer=predict__pb2.PredictRequest.SerializeToString,
                response_deserializer=predict__pb2.PredictResponse.FromString,
                )
        self.predict_ack = channel.unary_stream(
                '/model_serving.ModelServing/predict_ack',
                request_serializer=predict__pb2.ClientToken.SerializeToString,
                response_deserializer=predict__pb2.PredictRequestAck.FromString,
                )
        self.register = channel.unary_unary(
                '/model_serving.ModelServing/register',
                request_serializer=predict__pb2.RegisterRequest.SerializeToString,
                response_deserializer=predict__pb2.RegisterResponse.FromString,
                )
        self.unregister = channel.unary_unary(
                '/model_serving.ModelServing/unregister',
                request_serializer=predict__pb2.ClientToken.SerializeToString,
                response_deserializer=predict__pb2.Empty.FromString,
                )


class ModelServingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def predict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def predict_ack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'predict': grpc.stream_stream_rpc_method_handler(
                    servicer.predict,
                    request_deserializer=predict__pb2.PredictRequest.FromString,
                    response_serializer=predict__pb2.PredictResponse.SerializeToString,
            ),
            'predict_ack': grpc.unary_stream_rpc_method_handler(
                    servicer.predict_ack,
                    request_deserializer=predict__pb2.ClientToken.FromString,
                    response_serializer=predict__pb2.PredictRequestAck.SerializeToString,
            ),
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=predict__pb2.RegisterRequest.FromString,
                    response_serializer=predict__pb2.RegisterResponse.SerializeToString,
            ),
            'unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.unregister,
                    request_deserializer=predict__pb2.ClientToken.FromString,
                    response_serializer=predict__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_serving.ModelServing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelServing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def predict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/model_serving.ModelServing/predict',
            predict__pb2.PredictRequest.SerializeToString,
            predict__pb2.PredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def predict_ack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/model_serving.ModelServing/predict_ack',
            predict__pb2.ClientToken.SerializeToString,
            predict__pb2.PredictRequestAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model_serving.ModelServing/register',
            predict__pb2.RegisterRequest.SerializeToString,
            predict__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model_serving.ModelServing/unregister',
            predict__pb2.ClientToken.SerializeToString,
            predict__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
